# Generated by Django 4.2.6 on 2023-10-26 09:06

import agreement.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_date', models.DateField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=80)),
                ('company_name', models.CharField(max_length=100)),
                ('tax_number', models.CharField(max_length=20)),
                ('business_address_line_1', models.CharField(max_length=80)),
                ('business_address_line_2', models.CharField(max_length=80)),
                ('business_zip_code', models.CharField(max_length=10)),
                ('business_city', models.CharField(max_length=40)),
                ('business_country', models.CharField(max_length=40)),
                ('shipping_address_line_1', models.CharField(max_length=80)),
                ('shipping_address_line_2', models.CharField(max_length=80)),
                ('shipping_zip_code', models.CharField(max_length=10)),
                ('shipping_city', models.CharField(max_length=40)),
                ('shipping_country', models.CharField(max_length=40)),
                ('correspondence_address_line_1', models.CharField(max_length=80)),
                ('correspondence_address_line_2', models.CharField(max_length=80)),
                ('correspondence_zip_code', models.CharField(max_length=10)),
                ('correspondence_city', models.CharField(max_length=40)),
                ('correspondence_country', models.CharField(max_length=40)),
                ('email_1', models.EmailField(max_length=254)),
                ('email_2', models.EmailField(max_length=254)),
                ('phone_no_1', models.CharField(max_length=20)),
                ('phone_no_2', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('no_of_items', models.PositiveSmallIntegerField()),
                ('agreement_length', models.PositiveSmallIntegerField(choices=[(12, '12M'), (24, '24M'), (36, '36M')], default=24)),
                ('additional_info', models.TextField(validators=[agreement.models.validate_no_bad_words])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='agreement', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
