# Generated by Django 4.2.6 on 2023-10-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0002_alter_agreement_correspondence_address_line_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='business_address_line_2',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
