# Generated by Django 4.2.6 on 2023-10-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0006_alter_agreement_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='agreement_length',
            field=models.CharField(choices=[(12, '12M'), (24, '24M'), (36, '36M')], default=24, max_length=5),
        ),
    ]
